#!/bin/bash
# Arch Linux 换源模块

apply_arch_mirrors() {
    local source="$1" protocol="$2"

    if [[ "$USE_OFFICIAL_SOURCE" == "true" ]]; then
        cat > /etc/pacman.d/mirrorlist <<'EOF'
## Arch Linux official mirrorlist
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
EOF
        success "已恢复官方源"
        return
    fi

    cat > /etc/pacman.d/mirrorlist <<EOF
## Arch Linux mirrorlist -- Generated by ChangeMirrors
Server = ${protocol}://${source}/archlinux/\$repo/os/\$arch
EOF
    success "已写入 /etc/pacman.d/mirrorlist"

    # 同步数据库
    if confirm_action "是否立即同步软件包数据库?"; then
        pacman -Syy
    fi
}